### ISSUE TITLE
Windows Virus protection tags this as a Trojan

### ISSUE THREAD

**Issue by yeli23** [shaobaili3/LoR_Master_previous#1]
I ran this once a few days with no problem but as of today it gets marked as "Trojan:Win32/Fuerboos.E!cl" I assume this is a false alarm but just wanted you to know.

**Comment by shaobaili3** [comment]
Thanks for your feedback.

This project packaged by Pyinstaller which may be detected as Anti-Virus Trojan: Win32 by Anti-Virus Software. This warning may get fixed after the virus database updated globally by more users adding to the white list, but once I released the new version the warning come back. Unfortunately, I cannot afford the expensive personal software signature/certificate currently. It may persist as a long term issue.

LoR Master Tracker will be open source in the next version as planned. You can replace the riot API and build the project on your own soon. It should be a good solution for some users.
